// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250422165455_career")]
    partial class career
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.About", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CEOBody")
                        .HasColumnType("longtext")
                        .HasColumnName("ceo_body");

                    b.Property<string>("CEOImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("ceo_image_path");

                    b.Property<string>("CEOName")
                        .HasColumnType("longtext")
                        .HasColumnName("ceo_name");

                    b.Property<string>("CEOTagline")
                        .HasColumnType("longtext")
                        .HasColumnName("ceo_tagline");

                    b.Property<string>("Count1")
                        .HasColumnType("longtext")
                        .HasColumnName("count1");

                    b.Property<string>("Count1ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("count1image_path");

                    b.Property<string>("Count2")
                        .HasColumnType("longtext")
                        .HasColumnName("count2");

                    b.Property<string>("Count2ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("count2image_path");

                    b.Property<string>("Count3")
                        .HasColumnType("longtext")
                        .HasColumnName("count3");

                    b.Property<string>("Count3ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("count3image_path");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("HomeBody")
                        .HasColumnType("longtext")
                        .HasColumnName("home_body");

                    b.Property<string>("HomeImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_path");

                    b.Property<string>("HomeTagline")
                        .HasColumnType("longtext")
                        .HasColumnName("home_tagline");

                    b.Property<string>("HomeTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("home_title");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label1")
                        .HasColumnType("longtext")
                        .HasColumnName("label1");

                    b.Property<string>("Label2")
                        .HasColumnType("longtext")
                        .HasColumnName("label2");

                    b.Property<string>("Label3")
                        .HasColumnType("longtext")
                        .HasColumnName("label3");

                    b.Property<string>("MissionBody")
                        .HasColumnType("longtext")
                        .HasColumnName("mission_body");

                    b.Property<string>("MissionTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("mission_title");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("TestimonialTagline")
                        .HasColumnType("longtext")
                        .HasColumnName("testimonial_tagline");

                    b.Property<string>("TestimonialTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("testimonial_title");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("ValuesBody")
                        .HasColumnType("longtext")
                        .HasColumnName("values_body");

                    b.Property<string>("ValuesTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("values_title");

                    b.Property<string>("VideoAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("video_alt");

                    b.Property<string>("VideoPath")
                        .HasColumnType("longtext")
                        .HasColumnName("video_path");

                    b.Property<string>("VisionBody")
                        .HasColumnType("longtext")
                        .HasColumnName("vision_body");

                    b.Property<string>("VisionMissionBody")
                        .HasColumnType("longtext")
                        .HasColumnName("vision_mission_body");

                    b.Property<string>("VisionMissionHeading")
                        .HasColumnType("longtext")
                        .HasColumnName("vision_mission_heading");

                    b.Property<string>("VisionMissionImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("vision_mission_image_path");

                    b.Property<string>("VisionTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("vision_title");

                    b.HasKey("Id")
                        .HasName("pk_about");

                    b.ToTable("about", (string)null);
                });

            modelBuilder.Entity("Domain.AboutGallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.HasKey("Id")
                        .HasName("pk_about_gallery");

                    b.ToTable("about_gallery", (string)null);
                });

            modelBuilder.Entity("Domain.Career", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("Body2")
                        .HasColumnType("longtext")
                        .HasColumnName("body2");

                    b.Property<string>("Body3")
                        .HasColumnType("longtext")
                        .HasColumnName("body3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IconAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_alt");

                    b.Property<string>("IconPath")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobType")
                        .HasColumnType("longtext")
                        .HasColumnName("job_type");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Title2")
                        .HasColumnType("longtext")
                        .HasColumnName("title2");

                    b.Property<string>("Title3")
                        .HasColumnType("longtext")
                        .HasColumnName("title3");

                    b.Property<long?>("Vacancy")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy");

                    b.HasKey("Id")
                        .HasName("pk_career");

                    b.ToTable("career", (string)null);
                });

            modelBuilder.Entity("Domain.CareerSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("FormTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("form_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_career_section");

                    b.ToTable("career_section", (string)null);
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("AppointmentImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("appointment_image_alt");

                    b.Property<string>("AppointmentImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("appointment_image_path");

                    b.Property<string>("AppointmentLabel")
                        .HasColumnType("longtext")
                        .HasColumnName("appointment_label");

                    b.Property<string>("AppointmentPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("appointment_phone");

                    b.Property<string>("Certificate1ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("certificate1image_alt");

                    b.Property<string>("Certificate1ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("certificate1image_path");

                    b.Property<string>("Certificate2ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("certificate2image_alt");

                    b.Property<string>("Certificate2ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("certificate2image_path");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Email1")
                        .HasColumnType("longtext")
                        .HasColumnName("email1");

                    b.Property<string>("Email2")
                        .HasColumnType("longtext")
                        .HasColumnName("email2");

                    b.Property<string>("FooterTimingLabel1")
                        .HasColumnType("longtext")
                        .HasColumnName("footer_timing_label1");

                    b.Property<string>("FooterTimingLabel2")
                        .HasColumnType("longtext")
                        .HasColumnName("footer_timing_label2");

                    b.Property<string>("FooterTimingLabel3")
                        .HasColumnType("longtext")
                        .HasColumnName("footer_timing_label3");

                    b.Property<string>("FooterTimingLabel4")
                        .HasColumnType("longtext")
                        .HasColumnName("footer_timing_label4");

                    b.Property<string>("FormTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("form_title");

                    b.Property<string>("GoogleMapLink")
                        .HasColumnType("longtext")
                        .HasColumnName("google_map_link");

                    b.Property<string>("HeaderEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("header_email");

                    b.Property<string>("HeaderPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("header_phone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArabicEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_arabic_enabled");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Phone1")
                        .HasColumnType("longtext")
                        .HasColumnName("phone1");

                    b.Property<string>("Phone2")
                        .HasColumnType("longtext")
                        .HasColumnName("phone2");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Domain.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("Domain.Enquiry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AttachedFilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("attached_file_path");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_enquiry");

                    b.ToTable("enquiry", (string)null);
                });

            modelBuilder.Entity("Domain.Faq", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_faq");

                    b.ToTable("faq", (string)null);
                });

            modelBuilder.Entity("Domain.Framework.Email", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("EmailId")
                        .HasColumnType("longtext")
                        .HasColumnName("email_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<string>("Recipients")
                        .HasColumnType("longtext")
                        .HasColumnName("recipients");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("longtext")
                        .HasColumnName("smtp_server");

                    b.HasKey("Id")
                        .HasName("pk_email");

                    b.ToTable("email", (string)null);
                });

            modelBuilder.Entity("Domain.HomeBanner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("ButtonTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("button_title");

                    b.Property<string>("ButtonUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("button_url");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImageArabicAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_arabic_alt");

                    b.Property<string>("ImageArabicPath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_arabic_path");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_home_banner");

                    b.ToTable("home_banner", (string)null);
                });

            modelBuilder.Entity("Domain.Insurance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_insurance");

                    b.ToTable("insurance", (string)null);
                });

            modelBuilder.Entity("Domain.InsuranceSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_insurance_section");

                    b.ToTable("insurance_section", (string)null);
                });

            modelBuilder.Entity("Domain.Loyalty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("HomeImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_alt");

                    b.Property<string>("HomeImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_loyalty");

                    b.ToTable("loyalty", (string)null);
                });

            modelBuilder.Entity("Domain.LoyaltyImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LoyaltyId")
                        .HasColumnType("bigint")
                        .HasColumnName("loyalty_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_image");

                    b.ToTable("loyalty_image", (string)null);
                });

            modelBuilder.Entity("Domain.News", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("HomeImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_alt");

                    b.Property<string>("HomeImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("PostDate")
                        .HasColumnType("longtext")
                        .HasColumnName("post_date");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("Domain.NewsImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<long>("NewsId")
                        .HasColumnType("bigint")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_news_image");

                    b.ToTable("news_image", (string)null);
                });

            modelBuilder.Entity("Domain.PageSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerArabicImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_arabic_image_path");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerSubTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_sub_title");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext")
                        .HasColumnName("parent_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<bool>("ShowOnFooter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_on_footer");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_page_settings");

                    b.ToTable("page_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Home\",\"ar\":\"AHome\"}"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "our-center",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Our Center\",\"ar\":\"AOur Center\"}"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "services",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Our Services\",\"ar\":\"AOur Services\"}"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 4L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "team",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Our Team\",\"ar\":\"AOur Team\"}"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 5L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "partners",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Our Partners\",\"ar\":\"AOur Partners\"}"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 6L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "loyalty-program",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Loyalty Program\",\"ar\":\"ALoyalty Program\"}"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 7L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "contact",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Contact Us\",\"ar\":\"AContact Us\"}"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 8L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "privacy-policy",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Privacy Policy\",\"ar\":\"APrivacy Policy\"}"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 9L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "faq",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"FAQ\",\"ar\":\"AFAQ\"}"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 10L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "news",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"News\",\"ar\":\"ANews\"}"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 11L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "insurance",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Insurance\",\"ar\":\"AInsurance\"}"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 12L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "video-hub",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Video Hub\",\"ar\":\"AVideo Hub\"}"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 13L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "careers",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Careers\",\"ar\":\"ACareers\"}"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 14L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "result",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Result\",\"ar\":\"AResult\"}"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 15L,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "error",
                            ParentName = "index",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Error\",\"ar\":\"AError\"}"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 16L,
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "appointment",
                            ParentName = "about",
                            ShowOnFooter = false,
                            Title = "{\"en\":\"Book Appointment\",\"ar\":\"ABook Appointment\"}"
                        });
                });

            modelBuilder.Entity("Domain.Partner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LogoPath")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_path");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<long>("PartnerCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_category_id");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_partner");

                    b.ToTable("partner", (string)null);
                });

            modelBuilder.Entity("Domain.PartnerCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_partner_category");

                    b.ToTable("partner_category", (string)null);
                });

            modelBuilder.Entity("Domain.PartnerSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("HomeBody")
                        .HasColumnType("longtext")
                        .HasColumnName("home_body");

                    b.Property<string>("HomeTagline")
                        .HasColumnType("longtext")
                        .HasColumnName("home_tagline");

                    b.Property<string>("HomeTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("home_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_partner_section");

                    b.ToTable("partner_section", (string)null);
                });

            modelBuilder.Entity("Domain.Policy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_policy");

                    b.ToTable("policy", (string)null);
                });

            modelBuilder.Entity("Domain.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BannerImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_path");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_title");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("HomeImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_alt");

                    b.Property<string>("HomeImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("home_image_path");

                    b.Property<string>("IconAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_alt");

                    b.Property<string>("IconPath")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_path");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_on_home_page");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Domain.ServiceSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_service_section");

                    b.ToTable("service_section", (string)null);
                });

            modelBuilder.Entity("Domain.SocialMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_social_media");

                    b.ToTable("social_media", (string)null);
                });

            modelBuilder.Entity("Domain.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentIds")
                        .HasColumnType("longtext")
                        .HasColumnName("department_ids");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortBody")
                        .HasColumnType("longtext")
                        .HasColumnName("short_body");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_on_home_page");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("Domain.TeamContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_team_content");

                    b.ToTable("team_content", (string)null);
                });

            modelBuilder.Entity("Domain.TeamSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_team_section");

                    b.ToTable("team_section", (string)null);
                });

            modelBuilder.Entity("Domain.Testimonial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_testimonial");

                    b.ToTable("testimonial", (string)null);
                });

            modelBuilder.Entity("Domain.VideoHub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_video_hub");

                    b.ToTable("video_hub", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
